import { OpenApiGeneratorV3 } from '@asteasolutions/zod-to-openapi';
import { registry } from '../src/schemas';
import * as fs from 'fs';
import * as path from 'path';

const generator = new OpenApiGeneratorV3(registry.definitions);

const document = generator.generateDocument({
  openapi: '3.0.0',
  info: {
    title: 'Brand Service API',
    description:
      'Microservice for managing brand information, media assets, organization data, and AI-powered content analysis.',
    version: '1.0.0',
  },
  servers: [
    {
      url: process.env.BRAND_SERVICE_URL || 'http://localhost:3005',
    },
  ],
  security: [{ apiKey: [] }],
});

// Add security scheme and common parameters (not auto-generated by zod-to-openapi)
document.components = {
  ...document.components,
  securitySchemes: {
    apiKey: {
      type: 'apiKey',
      in: 'header',
      name: 'X-API-Key',
      description: 'Service-to-service API key',
    },
  },
  parameters: {
    'X-Org-Id': {
      name: 'X-Org-Id',
      in: 'header',
      required: true,
      schema: { type: 'string' },
      description: 'Internal organization UUID',
    },
    'X-User-Id': {
      name: 'X-User-Id',
      in: 'header',
      required: false,
      schema: { type: 'string' },
      description: 'Internal user UUID',
    },
    'X-Run-Id': {
      name: 'X-Run-Id',
      in: 'header',
      required: false,
      schema: { type: 'string' },
      description: 'Parent run ID for run tracking',
    },
    'X-Campaign-Id': {
      name: 'X-Campaign-Id',
      in: 'header',
      required: false,
      schema: { type: 'string' },
      description: 'Campaign ID (injected by workflow-service)',
    },
    'X-Brand-Id': {
      name: 'X-Brand-Id',
      in: 'header',
      required: false,
      schema: { type: 'string' },
      description: 'Comma-separated brand UUIDs (injected by workflow-service). Example: "uuid1,uuid2,uuid3". Single UUID for single-brand campaigns.',
      example: '550e8400-e29b-41d4-a716-446655440000,660e8400-e29b-41d4-a716-446655440001',
    },
    'X-Workflow-Slug': {
      name: 'X-Workflow-Slug',
      in: 'header',
      required: false,
      schema: { type: 'string' },
      description: 'Workflow slug (injected by workflow-service)',
    },
  },
};

const outputPath = path.resolve(__dirname, '../openapi.json');
fs.writeFileSync(outputPath, JSON.stringify(document, null, 2));
console.log('Generated openapi.json');
