import { OpenApiGeneratorV3 } from '@asteasolutions/zod-to-openapi';
import { registry } from '../src/schemas';
import * as fs from 'fs';
import * as path from 'path';

const generator = new OpenApiGeneratorV3(registry.definitions);

const document = generator.generateDocument({
  openapi: '3.0.0',
  info: {
    title: 'Brand Service API',
    description:
      'Microservice for managing brand information, sales profiles, media assets, organization data, and AI-powered content analysis.',
    version: '1.0.0',
  },
  servers: [
    {
      url: process.env.BRAND_SERVICE_URL || 'http://localhost:3005',
    },
  ],
  security: [{ apiKey: [] }],
});

// Add security scheme (not auto-generated by zod-to-openapi)
document.components = {
  ...document.components,
  securitySchemes: {
    apiKey: {
      type: 'apiKey',
      in: 'header',
      name: 'X-API-Key',
      description: 'Service-to-service API key',
    },
  },
};

const outputPath = path.resolve(__dirname, '../openapi.json');
fs.writeFileSync(outputPath, JSON.stringify(document, null, 2));
console.log('Generated openapi.json');
